# WebServer 配置文件

# 服务器配置
port=1316
trigMode=3
timeoutMS=60000
openLinger=false

# 数据库配置
sqlPort=3306
sqlUser=root
sqlPwd=123456
dbName=webserver
connPoolNum=12

# 线程池配置
threadNum=6

# 日志配置
openLog=true
logLevel=1
logQueSize=1024